version: "3.8"
services:
  odm:
    image: ibmcom/odm
    hostname: odm
    container_name: odm
    environment:
      - LICENSE=accept
      - SAMPLE=true
    healthcheck:
      test: curl -k -f http://localhost:9060/res/login.jsf || exit 1
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    ports:
      - 9060:9060
  backend:
    image: backend
    hostname: backend
    volumes:
      - ./data:/data
    build: rule-agent
    depends_on:
       odm:
         condition: service_healthy
    environment:
      - ODM_SERVER_URL=http://odm:9060
      - ODM_USERNAME=odmAdmin
      - ODM_PASSWORD=odmAdmin
      - PYTHONUNBUFFERED=1
      - DATADIR=/data
    env_file: 
      - "llm.env"
    ports:
      - 9000:9000
    extra_hosts:   
      - "host.containers.internal:host-gateway"
# If you are using Podman, comment out the line above and uncomment the following line with your IP address:
#      - "host.containers.internal:${HOST_IP_ADDRESS}"
  frontend:
    image: chatbot-frontend
    build: 
      context: chatbot-frontend
      args:
      - API_URL=http://localhost:9000
    depends_on:
      - backend
    ports:
      - 8080:80
